"""Concatenate parallel-chain MCMC chunks into a single dataset.

Each chunk is a tensor of shape (N_per_chunk, 1, L, L) generated by
`generate_mcmc_data.py -seed <S> -outPath <chunks/...>`. After
concatenation the combined tensor matches what a single sequential run
of `-N <N_total>` would produce, so downstream `generate_hs_samples.py`
sees no difference.

Usage:
    python concat_mcmc_chunks.py \
        --pattern 'data/mcmc_data/chunks/mcmc_wolff_L64_T*_N50000_seed*.pt' \
        --out data/mcmc_data/mcmc_wolff_L64_T2.269185314213022_N500000.pt
"""
import argparse
import glob
import os
import re
import sys

import torch


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pattern", required=True, help="glob for chunk files")
    p.add_argument("--out", required=True, help="output .pt path")
    p.add_argument("--expected-N", type=int, default=None,
                   help="(optional) sanity-check total sample count")
    args = p.parse_args()

    paths = sorted(glob.glob(args.pattern))
    if not paths:
        sys.exit(f"no chunks matched: {args.pattern}")

    # Sort by seed numerically so concat order is reproducible across reruns.
    def seed_of(p):
        m = re.search(r"seed(\d+)", p)
        return int(m.group(1)) if m else 0
    paths.sort(key=seed_of)

    print(f"found {len(paths)} chunks:")
    for p_ in paths:
        print(f"  {p_}")

    parts = []
    for p_ in paths:
        t = torch.load(p_, weights_only=True)
        print(f"  loaded {p_}  shape={tuple(t.shape)}")
        parts.append(t)

    out = torch.cat(parts, dim=0).contiguous().clone()
    print(f"concatenated shape: {tuple(out.shape)}")

    if args.expected_N is not None and out.shape[0] != args.expected_N:
        sys.exit(f"ERROR: expected N={args.expected_N}, got {out.shape[0]}")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    torch.save(out, args.out)
    sz = os.path.getsize(args.out) / 1e9
    print(f"wrote {args.out} ({sz:.2f} GB)")


if __name__ == "__main__":
    main()
